# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "kevinwang.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# Google tracking id to track your visitors

google-tracking-id: "UA-71683578-1"
# baseurl: /personal-jekyll-theme

# Google tracking id

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Kevin Wang"
title: "{ Kevin Wang }"
description: "Personal website and blog of Kevin Wang."
keywords: "kevin, wang, personal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/iceland.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Kevin Wang" 

me-img: "/img/homepage.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 8

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: True
pinterest-share: True
pocket-share: False
vkontakte-share: False

disqus-shortname: "kevinwangio"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/janestreet.jpg"
    date: "Winter '14, Summer '15, Aug '16 - Present"
    description: "Jane Street Capital: Software Engineer"

  - image: "/img/timeline/harvard.png"
    date: "Sept '12 - May '16"
    description: "Harvard University: A.B. and S.M. in CS"
  - image: "/img/timeline/harvard.png"
    date: "Spring '14, '15, & '16"
    description: "Harvard SEAS: Teaching Fellow"
  - image: "/img/timeline/google.png"
    date: "Summer '14"
    description: "Google Inc: Software Engineering Intern"

# First image of the Timeline

timeline-img: "/img/timeline/pokemon.gif"

###########
# Contact #
###########

email: "kevin@kevinwang.io"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: 
# author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/kevinwang.io"
  - title: "twitter"
    url: "https://twitter.com/kevintriguing"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/kevin-wang-io"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Travel: 'travel'
  Blog: 'latest-post'
  Contact: 'contact'
  

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
